default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: cxrep_development

test:
  <<: *default
  database: cxrep_test

production:
  primary: &primary_production
    <<: *default
    database: cxrep_production
    username: cxrep
    password: <%= ENV['CXREP_DATABASE_PASSWORD'] %>
  cache:
    <<: *primary_production
    database: cxrep_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cxrep_production_queue
    migrations_paths: db/queue_migrate
